name: Deploy Site
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  deploy:
    uses: "noelmiller/pelican/.github/workflows/github_pages.yml@decouple_build_workflow"
    with:
      settings: "publishconf.py"
      requirements: "-r requirements.txt"
